### ISSUE TITLE
DaggerApplicationComponent

### ISSUE THREAD

**Issue by haroonhassan** [hyperledger/iroha-android#129]
Hi there, trying to emulate the sample app, and Android Studio can't resolve the DaggerApplicationComponent. Any advice would be much appreciated, thank you.

**Comment by mrZizik** [comment]
Hello, @haroonhassan . First of all try to clean and rebuild project. DaggerApplicationComponent class should be autogenerated while building.

**Comment by haroonhassan** [comment]
@mrZizik thanks, that cleared it up. I was wondering if I could get some advise...apologise if this is the wrong forum for that. But would the sdk (and the other SDKs) allow the downloading client to join a network as a node that validates transactions? Or does this enable the sending of transactions, and querying of a ledger? 

The general use case I am considering is this: I want to build an app that will allow clients to participate as peers in a network..so the app would need to be installed natively as opposed to using the docker pardigm for hyperledger fabric. 

thanks in advance.

**Comment by mrZizik** [comment]
@haroonhassan, about adding clients as nodes: it's not in our priority list for now, but we'll think about it after getting to RC.
