### ISSUE TITLE
Can not share money beetwen two devices 

### ISSUE THREAD

**Issue by Gelassen** [hyperledger/iroha-android#75]
### The issue 
From physical device scan QR code of app on emulator and make a transfer. However even after half an hour app on emulator hasn't receive the money

### Environment
Nexus 7, Android 4.4.
Genymotion emulator, Android 5.0

### Steps to reproduce
1. Run application on both devices
2. Register users with two different names
3. Take a physical device and sent money to app on emulator
4. Get a confirmation dialog that;s transfer pass well
5. Wait some period of time to let devices sync up (up to 30 minutes)

### Observed behavior 
Amount of money on both devices remain the same

### Expected behavior
In a few minutes amount of money on physical device reduce on value equal to value in transaction and amount of money on emulator increase on the value equal to value in transaction

**Comment by takemiyamakoto** [comment]
What server is your app connecting to?

**Comment by Gelassen** [comment]
I use the sample and connect under the hood it use this server https://point-demo.iroha.tech (which is unavailable for now)

**Comment by Gelassen** [comment]
The context. My team and me plan to use this sample as a part of the demo for our solution for hackathon. We have the issue if that server doesn't work. 

Could you please provide your tech guidance how to make it work on our side or deploy our own server into the cloud?

**Comment by kobaken0029** [comment]
Sorry, this issue is client problem. not server. Caused by missing transfer command.
○ transfer
× Transfer
I will fix it as soon as possible then merge to master from develop.

To tell the truth, this issue is fixed on [iroha-demo-android](https://github.com/soramitsu/iroha-demo-android).
Very thanks!

**Comment by kobaken0029** [comment]
This issue was solved by #77's PR!

**Comment by Gelassen** [comment]
Confirm. It works now
